export const GET_SESSION = 'GET_SESSION';
export const GET_SESSIONS = 'GET_SESSIONS';
export const STORE_SESSION = 'STORE_SESSION';

export const GET_SESSIONS_SUCCESSFUL = 'GET_SESSIONS_SUCCESSFUL';
export const GET_SESSIONS_UNSUCCESSFUL = 'GET_SESSIONS_UNSUCCESSFUL';

export const RESET_STORE_SESSION_STATUS = 'RESET_STORE_SESSION_STATUS';

export const STORE_SESSION_WAS_SUCCESSFUL = 'STORE_SESSION_WAS_SUCCESSFUL';
export const STORE_SESSION_WAS_UNSUCCESSFUL = 'STORE_SESSION_WAS_UNSUCCESSFUL';

export const UPDATE_SESSION_WAS_SUCCESSFUL = 'UPDATE_SESSION_WAS_SUCCESSFUL';
export const UPDATE_SESSION_WAS_UNSUCCESSFUL = 'UPDATE_SESSION_WAS_UNSUCCESSFUL';

export const DELETE_SESSION_WAS_SUCCESSFUL = 'DELETE_SESSION_WAS_SUCCESSFUL';
export const DELETE_SESSION_WAS_UNSUCCESSFUL = 'DELETE_SESSION_WAS_UNSUCCESSFUL';

export const ACTIVATE_SESSION_WAS_SUCCESSFUL = 'ACTIVATE_SESSION_WAS_SUCCESSFUL';
export const ACTIVATE_SESSION_WAS_UNSUCCESSFUL = 'ACTIVATE_SESSION_WAS_UNSUCCESSFUL';