export { default } from './StudentMessageContainer.component';

export const GET_USER_MESSAGES_WAS_SUCCESSFUL = 'GET_USER_MESSAGES_WAS_SUCCESSFUL';
export const GET_USER_MESSAGES_WAS_UNSUCCESSFUL = 'GET_USER_MESSAGES_WAS_UNSUCCESSFUL';

export const SEND_MESSAGE_WAS_SUCCESSFUL = 'SEND_MESSAGE_WAS_SUCCESSFUL';
export const SEND_MESSAGE_WAS_UNSUCCESSFUL = 'SEND_MESSAGE_WAS_UNSUCCESSFUL';