export { default } from './ForumManagement.page.js';

export const GET_FORUM_SUCCESSFUL = 'GET_FORUM_SUCCESSFUL';
export const GET_FORUM_UNSUCCESSFUL = 'GET_FORUM_UNSUCCESSFUL';
export const UPDATE_FORUM_SUCCESSFUL = 'UPDATE_FORUM_SUCCESSFUL';
export const UPDATE_FORUM_UNSUCCESSFUL = 'UPDATE_FORUM_UNSUCCESSFUL';
export const RESET_UPDATE_FORUM_STATUS = 'RESET_UPDATE_FORUM_STATUS';