export { default } from './FacilitatorOutlineAddFeedback.page.js';

export const GET_OUTLINE_FEEDBACK_DATA_WAS_SUCCESSFUL = 'GET_OUTLINE_FEEDBACK_DATA_WAS_SUCCESSFUL';
export const GET_OUTLINE_FEEDBACK_DATA_WAS_UNSUCCESSFUL = 'GET_OUTLINE_FEEDBACK_DATA_WAS_UNSUCCESSFUL';

export const STORE_FEEDBACK_WAS_SUCCESSFUL = 'STORE_FEEDBACK_WAS_SUCCESSFUL';
export const STORE_FEEDBACK_WAS_UNSUCCESSFUL = 'STORE_FEEDBACK_WAS_UNSUCCESSFUL';

export const RESET_STORE_FEEDBACK = 'RESET_STORE_FEEDBACK';