export const GET_QUESTION = 'GET_QUESTION';

export const GET_QUESTIONS = 'GET_QUESTIONS';
export const STORE_QUESTION = 'STORE_QUESTION';

export const GET_QUESTIONS_SUCCESSFUL = 'GET_QUESTIONS_SUCCESSFUL';
export const GET_QUESTIONS_UNSUCCESSFUL = 'GET_QUESTIONS_UNSUCCESSFUL';

export const RESET_STORE_QUESTION_STATUS = 'RESET_STORE_QUESTION_STATUS';

export const STORE_QUESTION_WAS_SUCCESSFUL = 'STORE_QUESTION_WAS_SUCCESSFUL';
export const STORE_QUESTION_WAS_UNSUCCESSFUL = 'STORE_QUESTION_WAS_UNSUCCESSFUL';

export const UPDATE_QUESTION_WAS_SUCCESSFUL = 'UPDATE_QUESTION_WAS_SUCCESSFUL';
export const UPDATE_QUESTION_WAS_UNSUCCESSFUL = 'UPDATE_QUESTION_WAS_UNSUCCESSFUL';

export const DELETE_QUESTION_WAS_SUCCESSFUL = 'DELETE_QUESTION_WAS_SUCCESSFUL';
export const DELETE_QUESTION_WAS_UNSUCCESSFUL = 'DELETE_QUESTION_WAS_UNSUCCESSFUL';