export { default } from './MessageIndex.page';

export const GET_USER_AND_MESSAGE_COUNT_WAS_SUCCESSFUL = 'GET_USER_AND_MESSAGE_COUNT_WAS_SUCCESSFUL';
export const GET_USER_AND_MESSAGE_COUNT_WAS_UNSUCCESSFUL = 'GET_USER_AND_MESSAGE_COUNT_WAS_UNSUCCESSFUL';