export { default } from './ForumShow.page';

export const GET_ACTIVE_FORUM_COMMENT_WAS_SUCCESSFUL = 'GET_ACTIVE_FORUM_COMMENT_WAS_SUCCESSFUL';
export const GET_ACTIVE_FORUM_COMMENT_WAS_UNSUCCESSFUL = 'GET_ACTIVE_FORUM_COMMENT_WAS_UNSUCCESSFUL';

export const LIKE_COMMENT_WAS_SUCCESSFUL = 'LIKE_COMMENT_WAS_SUCCESSFUL';
export const LIKE_COMMENT_WAS_UNSUCCESSFUL = 'LIKE_COMMENT_WAS_UNSUCCESSFUL';