export { default } from './ProfilePayment.page';

export const GET_TRANSACTION_WAS_SUCCESSFUL = 'GET_TRANSACTION_WAS_SUCCESSFUL';
export const GET_TRANSACTION_WAS_UNSUCCESSFUL = 'GET_TRANSACTION_WAS_UNSUCCESSFUL';