export const GET_FACILITATOR_OUTLINE = 'GET_FACILITATOR_OUTLINE';
export const GET_FACILITATOR_OUTLINES = 'GET_FACILITATOR_OUTLINES';
export const STORE_FACILITATOR_OUTLINE = 'STORE_FACILITATOR_OUTLINE';

export const GET_FACILITATOR_OUTLINES_SUCCESSFUL = 'GET_FACILITATOR_OUTLINES_SUCCESSFUL';
export const GET_FACILITATOR_OUTLINES_UNSUCCESSFUL = 'GET_FACILITATOR_OUTLINES_UNSUCCESSFUL';

export const RESET_STORE_FACILITATOR_OUTLINE_STATUS = 'RESET_STORE_FACILITATOR_OUTLINE_STATUS';

export const STORE_FACILITATOR_OUTLINE_WAS_SUCCESSFUL = 'STORE_FACILITATOR_OUTLINE_WAS_SUCCESSFUL';
export const STORE_FACILITATOR_OUTLINE_WAS_UNSUCCESSFUL = 'STORE_FACILITATOR_OUTLINE_WAS_UNSUCCESSFUL';

export const UPDATE_FACILITATOR_OUTLINE_WAS_SUCCESSFUL = 'UPDATE_FACILITATOR_OUTLINE_WAS_SUCCESSFUL';
export const UPDATE_FACILITATOR_OUTLINE_WAS_UNSUCCESSFUL = 'UPDATE_FACILITATOR_OUTLINE_WAS_UNSUCCESSFUL';

export const DELETE_FACILITATOR_OUTLINE_WAS_SUCCESSFUL = 'DELETE_FACILITATOR_OUTLINE_WAS_SUCCESSFUL';
export const DELETE_FACILITATOR_OUTLINE_WAS_UNSUCCESSFUL = 'DELETE_FACILITATOR_OUTLINE_WAS_UNSUCCESSFUL';