export { default } from './DonateCreate.page';

export const DONATION_WAS_SUCCESSFUL = 'DONATION_WAS_SUCCESSFUL';
export const DONATION_WAS_UNSUCCESSFUL = 'DONATION_WAS_UNSUCCESSFUL';
export const RESET_DONATION_WAS_SUCCESSFUL_STATUS = 'RESET_DONATION_WAS_SUCCESSFUL_STATUS';