export { default } from './ProfileEditChangePassword.page';

export const RESET_PROFILE_STATUS = 'RESET_PROFILE_STATUS';
export const UPDATE_PASSWORD_WAS_SUCCESSFUL = 'UPDATE_PASSWORD_WAS_SUCCESSFUL'; 
export const UPDATE_PASSWORD_WAS_UNSUCCESSFUL = 'UPDATE_PASSWORD_WAS_UNSUCCESSFUL'; 