export { default } from './FeedbackGeneralCreate.page.js';

export const RESET_GENERAL_FEEDBACK_STATUS = 'RESET_GENERAL_FEEDBACK_STATUS';
export const GET_GENERAL_QUESTION_WAS_SUCCESSFUL = 'GET_GENERAL_QUESTION_WAS_SUCCESSFUL';
export const GET_GENERAL_QUESTION_WAS_UNSUCCESSFUL = 'GET_GENERAL_QUESTION_WAS_UNSUCCESSFUL';
export const STORE_GENERAL_FEEDBACK_WAS_SUCCESSFUL = 'STORE_GENERAL_FEEDBACK_WAS_SUCCESSFUL';
export const STORE_GENERAL_FEEDBACK_WAS_UNSUCCESSFUL = 'STORE_GENERAL_FEEDBACK_WAS_UNSUCCESSFUL';