export { default } from './SessionStudent.page.js';

export const GET_SESSION_STUDENT_SUCCESSFUL = 'GET_SESSION_STUDENT_SUCCESSFUL';
export const GET_SESSION_STUDENT_UNSUCCESSFUL = 'GET_SESSION_STUDENT_UNSUCCESSFUL';