export const GET_OUTLINE = 'GET_OUTLINE';
export const GET_OUTLINES = 'GET_OUTLINES';
export const STORE_OUTLINE = 'STORE_OUTLINE';

export const GET_OUTLINES_SUCCESSFUL = 'GET_OUTLINES_SUCCESSFUL';
export const GET_OUTLINES_UNSUCCESSFUL = 'GET_OUTLINES_UNSUCCESSFUL';

export const RESET_STORE_OUTLINE_STATUS = 'RESET_STORE_OUTLINE_STATUS';

export const STORE_OUTLINE_WAS_SUCCESSFUL = 'STORE_OUTLINE_WAS_SUCCESSFUL';
export const STORE_OUTLINE_WAS_UNSUCCESSFUL = 'STORE_OUTLINE_WAS_UNSUCCESSFUL';

export const UPDATE_OUTLINE_WAS_SUCCESSFUL = 'UPDATE_OUTLINE_WAS_SUCCESSFUL';
export const UPDATE_OUTLINE_WAS_UNSUCCESSFUL = 'UPDATE_OUTLINE_WAS_UNSUCCESSFUL';

export const DELETE_OUTLINE_WAS_SUCCESSFUL = 'DELETE_OUTLINE_WAS_SUCCESSFUL';
export const DELETE_OUTLINE_WAS_UNSUCCESSFUL = 'DELETE_OUTLINE_WAS_UNSUCCESSFUL';