export const GET_FACILITATOR = 'GET_FACILITATOR';
export const GET_FACILITATORS = 'GET_FACILITATORS';
export const STORE_FACILITATOR = 'STORE_FACILITATOR';

export const GET_FACILITATORS_SUCCESSFUL = 'GET_FACILITATORS_SUCCESSFUL';
export const GET_FACILITATORS_UNSUCCESSFUL = 'GET_FACILITATORS_UNSUCCESSFUL';

export const RESET_STORE_FACILITATOR_STATUS = 'RESET_STORE_FACILITATOR_STATUS';

export const STORE_FACILITATOR_WAS_SUCCESSFUL = 'STORE_FACILITATOR_WAS_SUCCESSFUL';
export const STORE_FACILITATOR_WAS_UNSUCCESSFUL = 'STORE_FACILITATOR_WAS_UNSUCCESSFUL';

export const UPDATE_FACILITATOR_WAS_SUCCESSFUL = 'UPDATE_FACILITATOR_WAS_SUCCESSFUL';
export const UPDATE_FACILITATOR_WAS_UNSUCCESSFUL = 'UPDATE_FACILITATOR_WAS_UNSUCCESSFUL';

export const DELETE_FACILITATOR_WAS_SUCCESSFUL = 'DELETE_FACILITATOR_WAS_SUCCESSFUL';
export const DELETE_FACILITATOR_WAS_UNSUCCESSFUL = 'DELETE_FACILITATOR_WAS_UNSUCCESSFUL';