export { default } from './ForumMyPostDeclined.page';

export const GET_ACTIVE_FORUM_WAS_SUCCESSFUL = 'GET_ACTIVE_FORUM_WAS_SUCCESSFUL';
export const GET_ACTIVE_FORUM_WAS_UNSUCCESSFUL = 'GET_ACTIVE_FORUM_WAS_UNSUCCESSFUL';