export { default } from './ForumCommentManagement.page.js';

export const GET_FORUM_COMMENT_SUCCESSFUL = 'GET_FORUM_COMMENT_SUCCESSFUL';
export const GET_FORUM_COMMENT_UNSUCCESSFUL = 'GET_FORUM_COMMENT_UNSUCCESSFUL';
export const UPDATE_FORUM_COMMENT_SUCCESSFUL = 'UPDATE_FORUM_COMMENT_SUCCESSFUL';
export const UPDATE_FORUM_COMMENT_UNSUCCESSFUL = 'UPDATE_FORUM_COMMENT_UNSUCCESSFUL';
export const RESET_UPDATE_FORUM_COMMENT_STATUS = 'RESET_UPDATE_FORUM_COMMENT_STATUS';