export { default } from './StudentSession.page.js';

export const GET_ACTIVE_AND_FUTURE_SESSION_SUCCESSFUL = 'GET_ACTIVE_AND_FUTURE_SESSION_SUCCESSFUL';
export const GET_ACTIVE_AND_FUTURE_SESSION_UNSUCCESSFUL = 'GET_ACTIVE_AND_FUTURE_SESSION_UNSUCCESSFUL';