export { default } from './StudentSession.page.js';

export const GET_ACTIVE_AND_FUTURE_SESSION_SUCCESSFUL = 'GET_ACTIVE_AND_FUTURE_SESSION_SUCCESSFUL';
export const GET_ACTIVE_AND_FUTURE_SESSION_UNSUCCESSFUL = 'GET_ACTIVE_AND_FUTURE_SESSION_UNSUCCESSFUL';

export const GET_SESSION_WAS_SUCCESSFUL = 'GET_SESSION_WAS_SUCCESSFUL'; 
export const GET_SESSION_WAS_UNSUCCESSFUL = 'GET_SESSION_WAS_UNSUCCESSFUL'; 

export const GET_SESSION_NUMBER_WAS_SUCCESSFUL = 'GET_SESSION_NUMBER_WAS_SUCCESSFUL';
export const GET_SESSION_NUMBER_WAS_UNSUCCESSFUL = 'GET_SESSION_NUMBER_WAS_UNSUCCESSFUL';

export const CONFIRM_TRANSACTION_WAS_SUCCESSFUL = 'CONFIRM_TRANSACTION_WAS_SUCCESSFUL';
export const CONFIRM_TRANSACTION_WAS_UNSUCCESSFUL = 'CONFIRM_TRANSACTION_WAS_UNSUCCESSFUL';

export const RESET_ONLINE_PAYMENT_TRANSACTION = 'RESET_ONLINE_PAYMENT_TRANSACTION';