export const GET_COURSE = 'GET_COURSE';
export const GET_COURSES = 'GET_COURSES';
export const STORE_COURSE = 'STORE_COURSE';

export const GET_COURSES_SUCCESSFUL = 'GET_COURSES_SUCCESSFUL';
export const GET_COURSES_UNSUCCESSFUL = 'GET_COURSES_UNSUCCESSFUL';

export const RESET_STORE_COURSE_STATUS = 'RESET_STORE_COURSE_STATUS';

export const STORE_COURSE_WAS_SUCCESSFUL = 'STORE_COURSE_WAS_SUCCESSFUL';
export const STORE_COURSE_WAS_UNSUCCESSFUL = 'STORE_COURSE_WAS_UNSUCCESSFUL';

export const UPDATE_COURSE_WAS_SUCCESSFUL = 'UPDATE_COURSE_WAS_SUCCESSFUL';
export const UPDATE_COURSE_WAS_UNSUCCESSFUL = 'UPDATE_COURSE_WAS_UNSUCCESSFUL';

export const DELETE_COURSE_WAS_SUCCESSFUL = 'DELETE_COURSE_WAS_SUCCESSFUL';
export const DELETE_COURSE_WAS_UNSUCCESSFUL = 'DELETE_COURSE_WAS_UNSUCCESSFUL';