export { default } from './ProfileIndex.page';

export const RESET_PROFILE_STATUS = 'RESET_PROFILE_STATUS';

export const GET_USER_PROFILE_SUCCESSFUL = 'GET_USER_PROFILE_SUCCESSFUL';
export const GET_USER_PROFILE_UNSUCCESSFUL = 'GET_USER_PROFILE_UNSUCCESSFUL';

export const UPDATE_USER_PROFILE_SUCCESSFUL = 'UPDATE_USER_PROFILE_SUCCESSFUL';
export const UPDATE_USER_PROFILE_UNSUCCESSFUL = 'UPDATE_USER_PROFILE_UNSUCCESSFUL';