export const GET_TRANSACTION_SUCCESSFUL = 'GET_TRANSACTION_SUCCESSFUL';
export const GET_TRANSACTION_UNSUCCESSFUL = 'GET_TRANSACTION_UNSUCCESSFUL';

export const UPDATE_TRANSACTION_SUCCESSFUL = 'UPDATE_TRANSACTION_SUCCESSFUL';
export const UPDATE_TRANSACTION_UNSUCCESSFUL = 'UPDATE_TRANSACTION_UNSUCCESSFUL';


export const RESET_UPDATE_TRANSACTION_STATUS = 'RESET_UPDATE_TRANSACTION_STATUS';